using System;
using System.ComponentModel.DataAnnotations;

namespace Tut5proj.DTOs.Requests
{
    public class EnrollStudentRequest
    {
        // in our case PK is not generated by db we have to manually set it up
        // [RegularExpression("^s[0-9]+$")]
        public string IndexNumber { get; set; }

        [Required]
        [MaxLength(100)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(100)]
        public string LastName { get; set; }

        // public DateTime BirthDate { get; set; }

        // public int IdEnrollment { get; set; }

        public DateTime BirthDate { get; set; }
        [Required]
        public string Studies { get; set; }

        [EmailAddress]
        public string Email { get; set; }

        [Range(18,99)]
        public int Age { get; set; }

    }
}